# Generated by Django 6.0.3 on 2026-05-04 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('year_of_foundation', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('imdb_code', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Animation', 'Animation')], max_length=20)),
                ('format', models.CharField(choices=[('Digital', 'Digital'), ('Blu-ray', 'Blu-ray'), ('DVD', 'DVD')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.productioncompany')),
            ],
        ),
    ]
